[package]
name = "dmenu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.1", features = ["derive"] }
gio = "0.19.2"
glib = "0.19.2"
